#!/usr/bin/env python3
"""Phase 25 — insert two-way-sync Fluent keys into the 17 non-English
locales. MT-flagged drafts matching the Standing Per-Phase Rules.
The 44 keys live as a single block at the end of each locale; the
English source in locales/en/freally.ftl is authoritative."""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALES_DIR = ROOT / "locales"

# 44 keys × 17 locales. MT-flagged; human review tracked in
# docs/I18N_TODO.md.
TRANSLATIONS = {
    "ar": {
        "footer_sync": "المزامنة",
        "title": "مزامنة ثنائية الاتجاه",
        "hint": "حافظ على تزامن مجلدين دون عمليات استبدال صامتة. تظهر التعديلات المتزامنة كنزاعات يمكنك حلها.",
        "add_pair": "إضافة زوج",
        "add_cancel": "إلغاء",
        "refresh": "تحديث",
        "add_save": "حفظ الزوج",
        "add_saving": "جارٍ الحفظ…",
        "add_missing": "التسمية والمسار الأيسر والمسار الأيمن مطلوبة جميعًا.",
        "remove_confirm": "إزالة زوج المزامنة هذا؟ يتم الاحتفاظ بقاعدة بيانات الحالة؛ لا يتم المساس بالمجلدات.",
        "field_label": "التسمية",
        "field_label_ph": "على سبيل المثال: المستندات ↔ NAS",
        "field_left": "المجلد الأيسر",
        "field_left_ph": "اختر أو الصق مسارًا مطلقًا",
        "field_right": "المجلد الأيمن",
        "field_right_ph": "اختر أو الصق مسارًا مطلقًا",
        "field_mode": "الوضع",
        "mode_two": "ثنائي الاتجاه",
        "mode_mlr": "مرآة (يسار → يمين)",
        "mode_mrl": "مرآة (يمين → يسار)",
        "mode_c": "مساهمة (يسار → يمين، بدون حذف)",
        "no_pairs": "لم يتم تكوين أي أزواج مزامنة بعد. انقر فوق \"إضافة زوج\" للبدء.",
        "loading": "تحميل الأزواج المكونة…",
        "never_run": "لم يتم التشغيل",
        "running": "قيد التشغيل",
        "run_now": "تشغيل الآن",
        "cancel": "إلغاء",
        "remove_pair": "إزالة",
        "view_conflicts": "عرض النزاعات ({ $count })",
        "conflicts_heading": "النزاعات",
        "no_conflicts": "لا توجد نزاعات من آخر تشغيل.",
        "winner": "الفائز",
        "side_ltr": "يسار",
        "side_rtl": "يمين",
        "kind_cw": "تعديل متزامن",
        "kind_de": "حذف ↔ تعديل",
        "kind_aa": "أضاف كلا الجانبين",
        "kind_ce": "تباعد المحتوى دون كتابة جديدة",
        "r_kl": "الاحتفاظ باليسار",
        "r_kr": "الاحتفاظ باليمين",
        "r_kb": "الاحتفاظ بكليهما",
        "r_3w": "حل عبر الدمج الثلاثي",
        "r_p53": "الدمج الثلاثي التفاعلي للملفات غير النصية يأتي في المرحلة 53.",
        "error_prefix": "خطأ في المزامنة",
    },
    "de": {
        "footer_sync": "Sync",
        "title": "Zwei-Wege-Synchronisation",
        "hint": "Halten Sie zwei Ordner ohne stille Überschreibungen synchron. Gleichzeitige Bearbeitungen erscheinen als auflösbare Konflikte.",
        "add_pair": "Paar hinzufügen",
        "add_cancel": "Abbrechen",
        "refresh": "Aktualisieren",
        "add_save": "Paar speichern",
        "add_saving": "Speichern…",
        "add_missing": "Bezeichnung, linker Pfad und rechter Pfad sind alle erforderlich.",
        "remove_confirm": "Dieses Sync-Paar entfernen? Die Zustandsdatenbank bleibt erhalten; die Ordner bleiben unberührt.",
        "field_label": "Bezeichnung",
        "field_label_ph": "z.B. Dokumente ↔ NAS",
        "field_left": "Linker Ordner",
        "field_left_ph": "Absoluten Pfad wählen oder einfügen",
        "field_right": "Rechter Ordner",
        "field_right_ph": "Absoluten Pfad wählen oder einfügen",
        "field_mode": "Modus",
        "mode_two": "Zwei-Wege",
        "mode_mlr": "Spiegel (links → rechts)",
        "mode_mrl": "Spiegel (rechts → links)",
        "mode_c": "Beitragen (links → rechts, keine Löschungen)",
        "no_pairs": "Noch keine Sync-Paare konfiguriert. Klicken Sie auf \"Paar hinzufügen\", um zu beginnen.",
        "loading": "Konfigurierte Paare werden geladen…",
        "never_run": "Nie ausgeführt",
        "running": "Läuft",
        "run_now": "Jetzt ausführen",
        "cancel": "Abbrechen",
        "remove_pair": "Entfernen",
        "view_conflicts": "Konflikte ansehen ({ $count })",
        "conflicts_heading": "Konflikte",
        "no_conflicts": "Keine Konflikte aus dem letzten Lauf.",
        "winner": "Sieger",
        "side_ltr": "links",
        "side_rtl": "rechts",
        "kind_cw": "Gleichzeitige Bearbeitung",
        "kind_de": "Löschen ↔ Bearbeiten",
        "kind_aa": "Beide Seiten hinzugefügt",
        "kind_ce": "Inhalt divergierte ohne neue Schreibung",
        "r_kl": "Links behalten",
        "r_kr": "Rechts behalten",
        "r_kb": "Beide behalten",
        "r_3w": "Über 3-Wege-Merge auflösen",
        "r_p53": "Interaktiver 3-Wege-Merge für Nicht-Text-Dateien landet in Phase 53.",
        "error_prefix": "Sync-Fehler",
    },
    "es": {
        "footer_sync": "Sinc",
        "title": "Sincronización bidireccional",
        "hint": "Mantenga dos carpetas sincronizadas sin sobrescrituras silenciosas. Las ediciones concurrentes aparecen como conflictos resolubles.",
        "add_pair": "Añadir par",
        "add_cancel": "Cancelar",
        "refresh": "Actualizar",
        "add_save": "Guardar par",
        "add_saving": "Guardando…",
        "add_missing": "La etiqueta, la ruta izquierda y la ruta derecha son todas obligatorias.",
        "remove_confirm": "¿Eliminar este par de sincronización? Se conserva la base de datos de estado; las carpetas permanecen intactas.",
        "field_label": "Etiqueta",
        "field_label_ph": "p. ej. Documentos ↔ NAS",
        "field_left": "Carpeta izquierda",
        "field_left_ph": "Elija o pegue una ruta absoluta",
        "field_right": "Carpeta derecha",
        "field_right_ph": "Elija o pegue una ruta absoluta",
        "field_mode": "Modo",
        "mode_two": "Bidireccional",
        "mode_mlr": "Espejo (izquierda → derecha)",
        "mode_mrl": "Espejo (derecha → izquierda)",
        "mode_c": "Contribuir (izquierda → derecha, sin borrados)",
        "no_pairs": "Aún no hay pares de sincronización configurados. Haga clic en \"Añadir par\" para empezar.",
        "loading": "Cargando pares configurados…",
        "never_run": "Nunca ejecutado",
        "running": "Ejecutando",
        "run_now": "Ejecutar ahora",
        "cancel": "Cancelar",
        "remove_pair": "Eliminar",
        "view_conflicts": "Ver conflictos ({ $count })",
        "conflicts_heading": "Conflictos",
        "no_conflicts": "Sin conflictos de la última ejecución.",
        "winner": "Ganador",
        "side_ltr": "izquierda",
        "side_rtl": "derecha",
        "kind_cw": "Edición concurrente",
        "kind_de": "Eliminar ↔ editar",
        "kind_aa": "Ambos lados añadieron",
        "kind_ce": "El contenido divergió sin una nueva escritura",
        "r_kl": "Conservar izquierda",
        "r_kr": "Conservar derecha",
        "r_kb": "Conservar ambos",
        "r_3w": "Resolver mediante fusión de 3 vías",
        "r_p53": "La fusión interactiva de 3 vías para archivos no textuales llega en la Fase 53.",
        "error_prefix": "Error de sincronización",
    },
    "fr": {
        "footer_sync": "Sync",
        "title": "Synchronisation bidirectionnelle",
        "hint": "Gardez deux dossiers synchronisés sans écrasements silencieux. Les modifications concurrentes apparaissent comme conflits résolubles.",
        "add_pair": "Ajouter une paire",
        "add_cancel": "Annuler",
        "refresh": "Actualiser",
        "add_save": "Enregistrer la paire",
        "add_saving": "Enregistrement…",
        "add_missing": "L'étiquette, le chemin gauche et le chemin droit sont tous obligatoires.",
        "remove_confirm": "Supprimer cette paire de synchronisation ? La base de données d'état est conservée ; les dossiers restent intacts.",
        "field_label": "Étiquette",
        "field_label_ph": "p. ex. Documents ↔ NAS",
        "field_left": "Dossier gauche",
        "field_left_ph": "Choisissez ou collez un chemin absolu",
        "field_right": "Dossier droit",
        "field_right_ph": "Choisissez ou collez un chemin absolu",
        "field_mode": "Mode",
        "mode_two": "Bidirectionnel",
        "mode_mlr": "Miroir (gauche → droite)",
        "mode_mrl": "Miroir (droite → gauche)",
        "mode_c": "Contribuer (gauche → droite, sans suppression)",
        "no_pairs": "Aucune paire de synchronisation configurée. Cliquez sur \"Ajouter une paire\" pour commencer.",
        "loading": "Chargement des paires configurées…",
        "never_run": "Jamais exécuté",
        "running": "En cours",
        "run_now": "Exécuter maintenant",
        "cancel": "Annuler",
        "remove_pair": "Supprimer",
        "view_conflicts": "Voir les conflits ({ $count })",
        "conflicts_heading": "Conflits",
        "no_conflicts": "Aucun conflit lors de la dernière exécution.",
        "winner": "Vainqueur",
        "side_ltr": "gauche",
        "side_rtl": "droite",
        "kind_cw": "Édition concurrente",
        "kind_de": "Suppression ↔ édition",
        "kind_aa": "Les deux côtés ont ajouté",
        "kind_ce": "Le contenu a divergé sans nouvelle écriture",
        "r_kl": "Conserver gauche",
        "r_kr": "Conserver droite",
        "r_kb": "Conserver les deux",
        "r_3w": "Résoudre via fusion à 3 voies",
        "r_p53": "La fusion interactive à 3 voies pour les fichiers non textuels arrive en Phase 53.",
        "error_prefix": "Erreur de synchronisation",
    },
    "hi": {
        "footer_sync": "सिंक",
        "title": "दो-तरफ़ा समन्वयन",
        "hint": "दो फ़ोल्डर्स को बिना मौन अधिलेखन के समन्वय में रखें। समवर्ती संपादन हल करने योग्य संघर्षों के रूप में प्रकट होते हैं।",
        "add_pair": "जोड़ी जोड़ें",
        "add_cancel": "रद्द करें",
        "refresh": "ताज़ा करें",
        "add_save": "जोड़ी सहेजें",
        "add_saving": "सहेज रहे हैं…",
        "add_missing": "लेबल, बायाँ पथ और दायाँ पथ सभी आवश्यक हैं।",
        "remove_confirm": "इस सिंक जोड़ी को हटाएँ? स्थिति डेटाबेस सुरक्षित रखा जाता है; फ़ोल्डर्स अछूते रहते हैं।",
        "field_label": "लेबल",
        "field_label_ph": "उदा. दस्तावेज़ ↔ NAS",
        "field_left": "बायाँ फ़ोल्डर",
        "field_left_ph": "एक पूर्ण पथ चुनें या चिपकाएँ",
        "field_right": "दायाँ फ़ोल्डर",
        "field_right_ph": "एक पूर्ण पथ चुनें या चिपकाएँ",
        "field_mode": "मोड",
        "mode_two": "दो-तरफ़ा",
        "mode_mlr": "दर्पण (बाएँ → दाएँ)",
        "mode_mrl": "दर्पण (दाएँ → बाएँ)",
        "mode_c": "योगदान (बाएँ → दाएँ, कोई विलोपन नहीं)",
        "no_pairs": "अभी तक कोई सिंक जोड़ी कॉन्फ़िगर नहीं है। शुरू करने के लिए \"जोड़ी जोड़ें\" पर क्लिक करें।",
        "loading": "कॉन्फ़िगर की गई जोड़ियाँ लोड हो रही हैं…",
        "never_run": "कभी नहीं चला",
        "running": "चल रहा है",
        "run_now": "अभी चलाएँ",
        "cancel": "रद्द करें",
        "remove_pair": "हटाएँ",
        "view_conflicts": "संघर्ष देखें ({ $count })",
        "conflicts_heading": "संघर्ष",
        "no_conflicts": "पिछले रन से कोई संघर्ष नहीं।",
        "winner": "विजेता",
        "side_ltr": "बायाँ",
        "side_rtl": "दायाँ",
        "kind_cw": "समवर्ती संपादन",
        "kind_de": "विलोपित ↔ संपादित",
        "kind_aa": "दोनों पक्षों ने जोड़ा",
        "kind_ce": "सामग्री नई लेखन के बिना विचलित हो गई",
        "r_kl": "बाएँ रखें",
        "r_kr": "दाएँ रखें",
        "r_kb": "दोनों रखें",
        "r_3w": "3-तरफ़ा मर्ज के माध्यम से हल करें",
        "r_p53": "गैर-पाठ फ़ाइलों के लिए इंटरैक्टिव 3-तरफ़ा मर्ज चरण 53 में आता है।",
        "error_prefix": "सिंक त्रुटि",
    },
    "id": {
        "footer_sync": "Sinkron",
        "title": "Sinkronisasi dua arah",
        "hint": "Jaga dua folder tetap sinkron tanpa penimpaan diam-diam. Pengeditan bersamaan muncul sebagai konflik yang dapat Anda selesaikan.",
        "add_pair": "Tambah pasangan",
        "add_cancel": "Batal",
        "refresh": "Segarkan",
        "add_save": "Simpan pasangan",
        "add_saving": "Menyimpan…",
        "add_missing": "Label, jalur kiri, dan jalur kanan semuanya wajib.",
        "remove_confirm": "Hapus pasangan sinkron ini? Basis data status dipertahankan; folder tidak tersentuh.",
        "field_label": "Label",
        "field_label_ph": "mis. Dokumen ↔ NAS",
        "field_left": "Folder kiri",
        "field_left_ph": "Pilih atau tempel jalur absolut",
        "field_right": "Folder kanan",
        "field_right_ph": "Pilih atau tempel jalur absolut",
        "field_mode": "Mode",
        "mode_two": "Dua arah",
        "mode_mlr": "Cermin (kiri → kanan)",
        "mode_mrl": "Cermin (kanan → kiri)",
        "mode_c": "Kontribusi (kiri → kanan, tanpa hapus)",
        "no_pairs": "Belum ada pasangan sinkron yang dikonfigurasi. Klik \"Tambah pasangan\" untuk memulai.",
        "loading": "Memuat pasangan yang dikonfigurasi…",
        "never_run": "Tidak pernah dijalankan",
        "running": "Berjalan",
        "run_now": "Jalankan sekarang",
        "cancel": "Batal",
        "remove_pair": "Hapus",
        "view_conflicts": "Lihat konflik ({ $count })",
        "conflicts_heading": "Konflik",
        "no_conflicts": "Tidak ada konflik dari jalannya terakhir.",
        "winner": "Pemenang",
        "side_ltr": "kiri",
        "side_rtl": "kanan",
        "kind_cw": "Pengeditan bersamaan",
        "kind_de": "Hapus ↔ sunting",
        "kind_aa": "Kedua sisi menambahkan",
        "kind_ce": "Konten menyimpang tanpa tulisan baru",
        "r_kl": "Pertahankan kiri",
        "r_kr": "Pertahankan kanan",
        "r_kb": "Pertahankan keduanya",
        "r_3w": "Selesaikan melalui penggabungan 3-arah",
        "r_p53": "Penggabungan 3-arah interaktif untuk berkas non-teks hadir di Fase 53.",
        "error_prefix": "Kesalahan sinkron",
    },
    "it": {
        "footer_sync": "Sinc",
        "title": "Sincronizzazione bidirezionale",
        "hint": "Mantieni due cartelle sincronizzate senza sovrascritture silenziose. Le modifiche concorrenti appaiono come conflitti risolvibili.",
        "add_pair": "Aggiungi coppia",
        "add_cancel": "Annulla",
        "refresh": "Aggiorna",
        "add_save": "Salva coppia",
        "add_saving": "Salvataggio…",
        "add_missing": "Etichetta, percorso sinistro e percorso destro sono tutti obbligatori.",
        "remove_confirm": "Rimuovere questa coppia di sincronizzazione? Il database di stato è preservato; le cartelle rimangono intatte.",
        "field_label": "Etichetta",
        "field_label_ph": "es. Documenti ↔ NAS",
        "field_left": "Cartella sinistra",
        "field_left_ph": "Scegli o incolla un percorso assoluto",
        "field_right": "Cartella destra",
        "field_right_ph": "Scegli o incolla un percorso assoluto",
        "field_mode": "Modalità",
        "mode_two": "Bidirezionale",
        "mode_mlr": "Specchio (sinistra → destra)",
        "mode_mrl": "Specchio (destra → sinistra)",
        "mode_c": "Contribuisci (sinistra → destra, senza eliminazioni)",
        "no_pairs": "Ancora nessuna coppia di sincronizzazione configurata. Clicca \"Aggiungi coppia\" per iniziare.",
        "loading": "Caricamento coppie configurate…",
        "never_run": "Mai eseguito",
        "running": "In esecuzione",
        "run_now": "Esegui ora",
        "cancel": "Annulla",
        "remove_pair": "Rimuovi",
        "view_conflicts": "Vedi conflitti ({ $count })",
        "conflicts_heading": "Conflitti",
        "no_conflicts": "Nessun conflitto dall'ultima esecuzione.",
        "winner": "Vincitore",
        "side_ltr": "sinistra",
        "side_rtl": "destra",
        "kind_cw": "Modifica concorrente",
        "kind_de": "Elimina ↔ modifica",
        "kind_aa": "Entrambi i lati hanno aggiunto",
        "kind_ce": "Il contenuto è divergito senza una nuova scrittura",
        "r_kl": "Mantieni sinistra",
        "r_kr": "Mantieni destra",
        "r_kb": "Mantieni entrambi",
        "r_3w": "Risolvi tramite unione a 3 vie",
        "r_p53": "L'unione interattiva a 3 vie per file non di testo arriva nella Fase 53.",
        "error_prefix": "Errore di sincronizzazione",
    },
    "ja": {
        "footer_sync": "同期",
        "title": "双方向同期",
        "hint": "2つのフォルダを静かな上書きなしで同期させます。同時編集は解決可能な競合として表示されます。",
        "add_pair": "ペアを追加",
        "add_cancel": "キャンセル",
        "refresh": "更新",
        "add_save": "ペアを保存",
        "add_saving": "保存中…",
        "add_missing": "ラベル、左のパス、右のパスはすべて必須です。",
        "remove_confirm": "この同期ペアを削除しますか? 状態データベースは保持され、フォルダには影響しません。",
        "field_label": "ラベル",
        "field_label_ph": "例: ドキュメント ↔ NAS",
        "field_left": "左フォルダ",
        "field_left_ph": "絶対パスを選択または貼り付け",
        "field_right": "右フォルダ",
        "field_right_ph": "絶対パスを選択または貼り付け",
        "field_mode": "モード",
        "mode_two": "双方向",
        "mode_mlr": "ミラー (左 → 右)",
        "mode_mrl": "ミラー (右 → 左)",
        "mode_c": "寄与 (左 → 右、削除なし)",
        "no_pairs": "まだ同期ペアは構成されていません。「ペアを追加」をクリックして始めてください。",
        "loading": "構成されたペアを読み込み中…",
        "never_run": "実行されていません",
        "running": "実行中",
        "run_now": "今すぐ実行",
        "cancel": "キャンセル",
        "remove_pair": "削除",
        "view_conflicts": "競合を表示 ({ $count })",
        "conflicts_heading": "競合",
        "no_conflicts": "前回の実行からの競合はありません。",
        "winner": "勝者",
        "side_ltr": "左",
        "side_rtl": "右",
        "kind_cw": "同時編集",
        "kind_de": "削除 ↔ 編集",
        "kind_aa": "両側で追加",
        "kind_ce": "新規書き込みなしでコンテンツが分岐",
        "r_kl": "左を保持",
        "r_kr": "右を保持",
        "r_kb": "両方を保持",
        "r_3w": "3方向マージで解決",
        "r_p53": "テキスト以外のファイル用のインタラクティブ3方向マージはフェーズ53で提供されます。",
        "error_prefix": "同期エラー",
    },
    "ko": {
        "footer_sync": "동기화",
        "title": "양방향 동기화",
        "hint": "두 폴더를 조용한 덮어쓰기 없이 동기화합니다. 동시 편집은 해결 가능한 충돌로 표시됩니다.",
        "add_pair": "쌍 추가",
        "add_cancel": "취소",
        "refresh": "새로 고침",
        "add_save": "쌍 저장",
        "add_saving": "저장 중…",
        "add_missing": "레이블, 왼쪽 경로, 오른쪽 경로는 모두 필수입니다.",
        "remove_confirm": "이 동기화 쌍을 제거하시겠습니까? 상태 데이터베이스는 보존되며 폴더는 영향을 받지 않습니다.",
        "field_label": "레이블",
        "field_label_ph": "예: 문서 ↔ NAS",
        "field_left": "왼쪽 폴더",
        "field_left_ph": "절대 경로를 선택하거나 붙여넣기",
        "field_right": "오른쪽 폴더",
        "field_right_ph": "절대 경로를 선택하거나 붙여넣기",
        "field_mode": "모드",
        "mode_two": "양방향",
        "mode_mlr": "미러 (왼쪽 → 오른쪽)",
        "mode_mrl": "미러 (오른쪽 → 왼쪽)",
        "mode_c": "기여 (왼쪽 → 오른쪽, 삭제 없음)",
        "no_pairs": "아직 구성된 동기화 쌍이 없습니다. \"쌍 추가\"를 클릭하여 시작하세요.",
        "loading": "구성된 쌍 로드 중…",
        "never_run": "실행된 적 없음",
        "running": "실행 중",
        "run_now": "지금 실행",
        "cancel": "취소",
        "remove_pair": "제거",
        "view_conflicts": "충돌 보기 ({ $count })",
        "conflicts_heading": "충돌",
        "no_conflicts": "마지막 실행의 충돌 없음.",
        "winner": "승자",
        "side_ltr": "왼쪽",
        "side_rtl": "오른쪽",
        "kind_cw": "동시 편집",
        "kind_de": "삭제 ↔ 편집",
        "kind_aa": "양쪽 모두 추가함",
        "kind_ce": "새로 쓰기 없이 내용이 분기됨",
        "r_kl": "왼쪽 유지",
        "r_kr": "오른쪽 유지",
        "r_kb": "둘 다 유지",
        "r_3w": "3-way 병합으로 해결",
        "r_p53": "비텍스트 파일을 위한 대화형 3-way 병합은 53단계에 제공됩니다.",
        "error_prefix": "동기화 오류",
    },
    "nl": {
        "footer_sync": "Sync",
        "title": "Tweewegsynchronisatie",
        "hint": "Houd twee mappen gesynchroniseerd zonder stille overschrijvingen. Gelijktijdige bewerkingen verschijnen als oplosbare conflicten.",
        "add_pair": "Paar toevoegen",
        "add_cancel": "Annuleren",
        "refresh": "Vernieuwen",
        "add_save": "Paar opslaan",
        "add_saving": "Opslaan…",
        "add_missing": "Label, linkerpad en rechterpad zijn allemaal vereist.",
        "remove_confirm": "Dit synchronisatiepaar verwijderen? De toestandsdatabase blijft behouden; de mappen blijven onaangetast.",
        "field_label": "Label",
        "field_label_ph": "bijv. Documenten ↔ NAS",
        "field_left": "Linkermap",
        "field_left_ph": "Kies of plak een absoluut pad",
        "field_right": "Rechtermap",
        "field_right_ph": "Kies of plak een absoluut pad",
        "field_mode": "Modus",
        "mode_two": "Tweeweg",
        "mode_mlr": "Spiegel (links → rechts)",
        "mode_mrl": "Spiegel (rechts → links)",
        "mode_c": "Bijdragen (links → rechts, geen verwijderingen)",
        "no_pairs": "Nog geen synchronisatieparen geconfigureerd. Klik op \"Paar toevoegen\" om te beginnen.",
        "loading": "Geconfigureerde paren laden…",
        "never_run": "Nooit uitgevoerd",
        "running": "Actief",
        "run_now": "Nu uitvoeren",
        "cancel": "Annuleren",
        "remove_pair": "Verwijderen",
        "view_conflicts": "Conflicten bekijken ({ $count })",
        "conflicts_heading": "Conflicten",
        "no_conflicts": "Geen conflicten van de laatste run.",
        "winner": "Winnaar",
        "side_ltr": "links",
        "side_rtl": "rechts",
        "kind_cw": "Gelijktijdige bewerking",
        "kind_de": "Verwijderen ↔ bewerken",
        "kind_aa": "Beide kanten hebben toegevoegd",
        "kind_ce": "Inhoud is divergiert zonder nieuwe schrijfactie",
        "r_kl": "Links behouden",
        "r_kr": "Rechts behouden",
        "r_kb": "Beide behouden",
        "r_3w": "Oplossen via 3-wegs samenvoegen",
        "r_p53": "Interactieve 3-wegs samenvoeging voor niet-tekstbestanden komt in fase 53.",
        "error_prefix": "Synchronisatiefout",
    },
    "pl": {
        "footer_sync": "Sync",
        "title": "Synchronizacja dwukierunkowa",
        "hint": "Utrzymuj dwa foldery zsynchronizowane bez cichych nadpisań. Równoczesne edycje pojawiają się jako konflikty do rozwiązania.",
        "add_pair": "Dodaj parę",
        "add_cancel": "Anuluj",
        "refresh": "Odśwież",
        "add_save": "Zapisz parę",
        "add_saving": "Zapisywanie…",
        "add_missing": "Etykieta, ścieżka lewa i ścieżka prawa są wszystkie wymagane.",
        "remove_confirm": "Usunąć tę parę synchronizacji? Baza danych stanu jest zachowywana; foldery pozostają nietknięte.",
        "field_label": "Etykieta",
        "field_label_ph": "np. Dokumenty ↔ NAS",
        "field_left": "Lewy folder",
        "field_left_ph": "Wybierz lub wklej ścieżkę absolutną",
        "field_right": "Prawy folder",
        "field_right_ph": "Wybierz lub wklej ścieżkę absolutną",
        "field_mode": "Tryb",
        "mode_two": "Dwukierunkowy",
        "mode_mlr": "Lustro (lewo → prawo)",
        "mode_mrl": "Lustro (prawo → lewo)",
        "mode_c": "Wkład (lewo → prawo, bez usuwania)",
        "no_pairs": "Brak skonfigurowanych par synchronizacji. Kliknij \"Dodaj parę\", aby rozpocząć.",
        "loading": "Ładowanie skonfigurowanych par…",
        "never_run": "Nigdy nie uruchomiono",
        "running": "Uruchomione",
        "run_now": "Uruchom teraz",
        "cancel": "Anuluj",
        "remove_pair": "Usuń",
        "view_conflicts": "Zobacz konflikty ({ $count })",
        "conflicts_heading": "Konflikty",
        "no_conflicts": "Brak konfliktów z ostatniego uruchomienia.",
        "winner": "Zwycięzca",
        "side_ltr": "lewy",
        "side_rtl": "prawy",
        "kind_cw": "Równoczesna edycja",
        "kind_de": "Usuń ↔ edytuj",
        "kind_aa": "Obie strony dodały",
        "kind_ce": "Zawartość rozeszła się bez nowego zapisu",
        "r_kl": "Zachowaj lewy",
        "r_kr": "Zachowaj prawy",
        "r_kb": "Zachowaj oba",
        "r_3w": "Rozwiąż przez scalanie trójdrożne",
        "r_p53": "Interaktywne scalanie trójdrożne dla plików nietekstowych pojawi się w fazie 53.",
        "error_prefix": "Błąd synchronizacji",
    },
    "pt-BR": {
        "footer_sync": "Sinc",
        "title": "Sincronização bidirecional",
        "hint": "Mantenha duas pastas sincronizadas sem sobrescritas silenciosas. Edições simultâneas aparecem como conflitos que você pode resolver.",
        "add_pair": "Adicionar par",
        "add_cancel": "Cancelar",
        "refresh": "Atualizar",
        "add_save": "Salvar par",
        "add_saving": "Salvando…",
        "add_missing": "Rótulo, caminho esquerdo e caminho direito são todos obrigatórios.",
        "remove_confirm": "Remover este par de sincronização? O banco de dados de estado é preservado; as pastas permanecem intactas.",
        "field_label": "Rótulo",
        "field_label_ph": "ex. Documentos ↔ NAS",
        "field_left": "Pasta esquerda",
        "field_left_ph": "Escolha ou cole um caminho absoluto",
        "field_right": "Pasta direita",
        "field_right_ph": "Escolha ou cole um caminho absoluto",
        "field_mode": "Modo",
        "mode_two": "Bidirecional",
        "mode_mlr": "Espelho (esquerda → direita)",
        "mode_mrl": "Espelho (direita → esquerda)",
        "mode_c": "Contribuir (esquerda → direita, sem exclusões)",
        "no_pairs": "Nenhum par de sincronização configurado ainda. Clique em \"Adicionar par\" para começar.",
        "loading": "Carregando pares configurados…",
        "never_run": "Nunca executado",
        "running": "Executando",
        "run_now": "Executar agora",
        "cancel": "Cancelar",
        "remove_pair": "Remover",
        "view_conflicts": "Ver conflitos ({ $count })",
        "conflicts_heading": "Conflitos",
        "no_conflicts": "Sem conflitos da última execução.",
        "winner": "Vencedor",
        "side_ltr": "esquerda",
        "side_rtl": "direita",
        "kind_cw": "Edição simultânea",
        "kind_de": "Excluir ↔ editar",
        "kind_aa": "Ambos os lados adicionaram",
        "kind_ce": "Conteúdo divergiu sem nova escrita",
        "r_kl": "Manter esquerda",
        "r_kr": "Manter direita",
        "r_kb": "Manter ambos",
        "r_3w": "Resolver via mesclagem de 3 vias",
        "r_p53": "A mesclagem interativa de 3 vias para arquivos não textuais chega na Fase 53.",
        "error_prefix": "Erro de sincronização",
    },
    "ru": {
        "footer_sync": "Синх",
        "title": "Двусторонняя синхронизация",
        "hint": "Поддерживайте синхронизацию двух папок без тихой перезаписи. Одновременные правки отображаются как разрешаемые конфликты.",
        "add_pair": "Добавить пару",
        "add_cancel": "Отмена",
        "refresh": "Обновить",
        "add_save": "Сохранить пару",
        "add_saving": "Сохранение…",
        "add_missing": "Метка, левый путь и правый путь все обязательны.",
        "remove_confirm": "Удалить эту пару синхронизации? База состояния сохраняется; папки остаются нетронутыми.",
        "field_label": "Метка",
        "field_label_ph": "напр. Документы ↔ NAS",
        "field_left": "Левая папка",
        "field_left_ph": "Выберите или вставьте абсолютный путь",
        "field_right": "Правая папка",
        "field_right_ph": "Выберите или вставьте абсолютный путь",
        "field_mode": "Режим",
        "mode_two": "Двусторонний",
        "mode_mlr": "Зеркало (слева → справа)",
        "mode_mrl": "Зеркало (справа → слева)",
        "mode_c": "Вклад (слева → справа, без удалений)",
        "no_pairs": "Пары синхронизации ещё не настроены. Нажмите \"Добавить пару\", чтобы начать.",
        "loading": "Загрузка настроенных пар…",
        "never_run": "Никогда не запускалось",
        "running": "Выполняется",
        "run_now": "Запустить сейчас",
        "cancel": "Отмена",
        "remove_pair": "Удалить",
        "view_conflicts": "Посмотреть конфликты ({ $count })",
        "conflicts_heading": "Конфликты",
        "no_conflicts": "Конфликтов с последнего запуска нет.",
        "winner": "Победитель",
        "side_ltr": "левый",
        "side_rtl": "правый",
        "kind_cw": "Одновременное редактирование",
        "kind_de": "Удаление ↔ редактирование",
        "kind_aa": "Обе стороны добавили",
        "kind_ce": "Содержимое разошлось без новой записи",
        "r_kl": "Оставить левый",
        "r_kr": "Оставить правый",
        "r_kb": "Оставить оба",
        "r_3w": "Разрешить через 3-стороннее слияние",
        "r_p53": "Интерактивное 3-стороннее слияние для нетекстовых файлов появится в фазе 53.",
        "error_prefix": "Ошибка синхронизации",
    },
    "tr": {
        "footer_sync": "Eşzm",
        "title": "Çift yönlü eşitleme",
        "hint": "İki klasörü sessiz üzerine yazmalar olmadan eşitleyin. Eşzamanlı düzenlemeler çözülebilir çatışmalar olarak görünür.",
        "add_pair": "Çift ekle",
        "add_cancel": "İptal",
        "refresh": "Yenile",
        "add_save": "Çifti kaydet",
        "add_saving": "Kaydediliyor…",
        "add_missing": "Etiket, sol yol ve sağ yol hepsi gereklidir.",
        "remove_confirm": "Bu eşitleme çiftini kaldır? Durum veritabanı korunur; klasörlere dokunulmaz.",
        "field_label": "Etiket",
        "field_label_ph": "örn. Belgeler ↔ NAS",
        "field_left": "Sol klasör",
        "field_left_ph": "Mutlak bir yol seçin veya yapıştırın",
        "field_right": "Sağ klasör",
        "field_right_ph": "Mutlak bir yol seçin veya yapıştırın",
        "field_mode": "Mod",
        "mode_two": "Çift yönlü",
        "mode_mlr": "Ayna (sol → sağ)",
        "mode_mrl": "Ayna (sağ → sol)",
        "mode_c": "Katkı (sol → sağ, silme yok)",
        "no_pairs": "Henüz yapılandırılmış eşitleme çifti yok. Başlamak için \"Çift ekle\" düğmesine tıklayın.",
        "loading": "Yapılandırılmış çiftler yükleniyor…",
        "never_run": "Hiç çalıştırılmadı",
        "running": "Çalışıyor",
        "run_now": "Şimdi çalıştır",
        "cancel": "İptal",
        "remove_pair": "Kaldır",
        "view_conflicts": "Çatışmaları görüntüle ({ $count })",
        "conflicts_heading": "Çatışmalar",
        "no_conflicts": "Son çalıştırmadan çatışma yok.",
        "winner": "Kazanan",
        "side_ltr": "sol",
        "side_rtl": "sağ",
        "kind_cw": "Eşzamanlı düzenleme",
        "kind_de": "Sil ↔ düzenle",
        "kind_aa": "Her iki taraf da ekledi",
        "kind_ce": "İçerik yeni bir yazma olmadan ayrıldı",
        "r_kl": "Solu tut",
        "r_kr": "Sağı tut",
        "r_kb": "İkisini de tut",
        "r_3w": "3-yönlü birleştirme ile çöz",
        "r_p53": "Metin dışı dosyalar için etkileşimli 3-yönlü birleştirme Faz 53'te gelir.",
        "error_prefix": "Eşitleme hatası",
    },
    "uk": {
        "footer_sync": "Синх",
        "title": "Двостороння синхронізація",
        "hint": "Тримайте дві теки синхронізованими без тихого перезапису. Одночасні редагування з'являються як розв'язувані конфлікти.",
        "add_pair": "Додати пару",
        "add_cancel": "Скасувати",
        "refresh": "Оновити",
        "add_save": "Зберегти пару",
        "add_saving": "Збереження…",
        "add_missing": "Мітка, лівий шлях і правий шлях — усе обов'язкове.",
        "remove_confirm": "Видалити цю пару синхронізації? Базу стану збережено; теки не змінено.",
        "field_label": "Мітка",
        "field_label_ph": "напр. Документи ↔ NAS",
        "field_left": "Ліва тека",
        "field_left_ph": "Виберіть або вставте абсолютний шлях",
        "field_right": "Права тека",
        "field_right_ph": "Виберіть або вставте абсолютний шлях",
        "field_mode": "Режим",
        "mode_two": "Двосторонній",
        "mode_mlr": "Дзеркало (ліво → право)",
        "mode_mrl": "Дзеркало (право → ліво)",
        "mode_c": "Внесок (ліво → право, без видалень)",
        "no_pairs": "Пари синхронізації ще не налаштовані. Натисніть \"Додати пару\", щоб почати.",
        "loading": "Завантаження налаштованих пар…",
        "never_run": "Ніколи не запускалося",
        "running": "Виконується",
        "run_now": "Запустити зараз",
        "cancel": "Скасувати",
        "remove_pair": "Видалити",
        "view_conflicts": "Переглянути конфлікти ({ $count })",
        "conflicts_heading": "Конфлікти",
        "no_conflicts": "Конфліктів з останнього запуску немає.",
        "winner": "Переможець",
        "side_ltr": "ліво",
        "side_rtl": "право",
        "kind_cw": "Одночасне редагування",
        "kind_de": "Видалити ↔ редагувати",
        "kind_aa": "Обидві сторони додали",
        "kind_ce": "Вміст розійшовся без нового запису",
        "r_kl": "Залишити ліво",
        "r_kr": "Залишити право",
        "r_kb": "Залишити обидва",
        "r_3w": "Вирішити через 3-сторонне об'єднання",
        "r_p53": "Інтерактивне 3-сторонне об'єднання для нетекстових файлів з'явиться у фазі 53.",
        "error_prefix": "Помилка синхронізації",
    },
    "vi": {
        "footer_sync": "Đồng bộ",
        "title": "Đồng bộ hai chiều",
        "hint": "Giữ hai thư mục đồng bộ mà không ghi đè âm thầm. Các chỉnh sửa đồng thời xuất hiện dưới dạng xung đột có thể giải quyết.",
        "add_pair": "Thêm cặp",
        "add_cancel": "Hủy",
        "refresh": "Làm mới",
        "add_save": "Lưu cặp",
        "add_saving": "Đang lưu…",
        "add_missing": "Nhãn, đường dẫn trái và đường dẫn phải đều bắt buộc.",
        "remove_confirm": "Xóa cặp đồng bộ này? Cơ sở dữ liệu trạng thái được giữ lại; các thư mục không bị ảnh hưởng.",
        "field_label": "Nhãn",
        "field_label_ph": "vd. Tài liệu ↔ NAS",
        "field_left": "Thư mục trái",
        "field_left_ph": "Chọn hoặc dán đường dẫn tuyệt đối",
        "field_right": "Thư mục phải",
        "field_right_ph": "Chọn hoặc dán đường dẫn tuyệt đối",
        "field_mode": "Chế độ",
        "mode_two": "Hai chiều",
        "mode_mlr": "Gương (trái → phải)",
        "mode_mrl": "Gương (phải → trái)",
        "mode_c": "Đóng góp (trái → phải, không xóa)",
        "no_pairs": "Chưa có cặp đồng bộ nào được cấu hình. Nhấp \"Thêm cặp\" để bắt đầu.",
        "loading": "Đang tải các cặp đã cấu hình…",
        "never_run": "Chưa bao giờ chạy",
        "running": "Đang chạy",
        "run_now": "Chạy ngay",
        "cancel": "Hủy",
        "remove_pair": "Xóa",
        "view_conflicts": "Xem xung đột ({ $count })",
        "conflicts_heading": "Xung đột",
        "no_conflicts": "Không có xung đột từ lần chạy cuối.",
        "winner": "Người thắng",
        "side_ltr": "trái",
        "side_rtl": "phải",
        "kind_cw": "Chỉnh sửa đồng thời",
        "kind_de": "Xóa ↔ sửa",
        "kind_aa": "Cả hai bên đều thêm",
        "kind_ce": "Nội dung đã phân kỳ mà không có ghi mới",
        "r_kl": "Giữ trái",
        "r_kr": "Giữ phải",
        "r_kb": "Giữ cả hai",
        "r_3w": "Giải quyết qua hợp nhất 3 chiều",
        "r_p53": "Hợp nhất 3 chiều tương tác cho các tệp không phải văn bản sẽ có trong Giai đoạn 53.",
        "error_prefix": "Lỗi đồng bộ",
    },
    "zh-CN": {
        "footer_sync": "同步",
        "title": "双向同步",
        "hint": "在不静默覆盖的情况下保持两个文件夹同步。并发编辑显示为可解决的冲突。",
        "add_pair": "添加对",
        "add_cancel": "取消",
        "refresh": "刷新",
        "add_save": "保存对",
        "add_saving": "保存中…",
        "add_missing": "标签、左侧路径和右侧路径都是必需的。",
        "remove_confirm": "删除此同步对?状态数据库被保留;文件夹未受影响。",
        "field_label": "标签",
        "field_label_ph": "例如 文档 ↔ NAS",
        "field_left": "左侧文件夹",
        "field_left_ph": "选择或粘贴绝对路径",
        "field_right": "右侧文件夹",
        "field_right_ph": "选择或粘贴绝对路径",
        "field_mode": "模式",
        "mode_two": "双向",
        "mode_mlr": "镜像 (左 → 右)",
        "mode_mrl": "镜像 (右 → 左)",
        "mode_c": "贡献 (左 → 右,无删除)",
        "no_pairs": "尚未配置同步对。点击\"添加对\"开始。",
        "loading": "正在加载已配置的对…",
        "never_run": "从未运行",
        "running": "运行中",
        "run_now": "立即运行",
        "cancel": "取消",
        "remove_pair": "删除",
        "view_conflicts": "查看冲突 ({ $count })",
        "conflicts_heading": "冲突",
        "no_conflicts": "上次运行没有冲突。",
        "winner": "胜者",
        "side_ltr": "左",
        "side_rtl": "右",
        "kind_cw": "并发编辑",
        "kind_de": "删除 ↔ 编辑",
        "kind_aa": "双方都添加了",
        "kind_ce": "内容在没有新写入的情况下发生分歧",
        "r_kl": "保留左侧",
        "r_kr": "保留右侧",
        "r_kb": "保留两者",
        "r_3w": "通过 3-way 合并解决",
        "r_p53": "非文本文件的交互式 3-way 合并将在第 53 阶段提供。",
        "error_prefix": "同步错误",
    },
}


def build_block(t: dict) -> str:
    return (
        "\n"
        "# Phase 25 — two-way sync with vector-clock conflict detection.\n"
        "# MT-flagged drafts; the authoritative English source lives in\n"
        "# locales/en/freally.ftl.\n"
        f"footer-sync = {t['footer_sync']}  # MT\n"
        f"sync-drawer-title = {t['title']}  # MT\n"
        f"sync-drawer-hint = {t['hint']}  # MT\n"
        f"sync-add-pair = {t['add_pair']}  # MT\n"
        f"sync-add-cancel = {t['add_cancel']}  # MT\n"
        f"sync-refresh = {t['refresh']}  # MT\n"
        f"sync-add-save = {t['add_save']}  # MT\n"
        f"sync-add-saving = {t['add_saving']}  # MT\n"
        f"sync-add-missing-fields = {t['add_missing']}  # MT\n"
        f"sync-remove-confirm = {t['remove_confirm']}  # MT\n"
        f"sync-field-label = {t['field_label']}  # MT\n"
        f"sync-field-label-placeholder = {t['field_label_ph']}  # MT\n"
        f"sync-field-left = {t['field_left']}  # MT\n"
        f"sync-field-left-placeholder = {t['field_left_ph']}  # MT\n"
        f"sync-field-right = {t['field_right']}  # MT\n"
        f"sync-field-right-placeholder = {t['field_right_ph']}  # MT\n"
        f"sync-field-mode = {t['field_mode']}  # MT\n"
        f"sync-mode-two-way = {t['mode_two']}  # MT\n"
        f"sync-mode-mirror-left-to-right = {t['mode_mlr']}  # MT\n"
        f"sync-mode-mirror-right-to-left = {t['mode_mrl']}  # MT\n"
        f"sync-mode-contribute-left-to-right = {t['mode_c']}  # MT\n"
        f"sync-no-pairs = {t['no_pairs']}  # MT\n"
        f"sync-loading = {t['loading']}  # MT\n"
        f"sync-never-run = {t['never_run']}  # MT\n"
        f"sync-running = {t['running']}  # MT\n"
        f"sync-run-now = {t['run_now']}  # MT\n"
        f"sync-cancel = {t['cancel']}  # MT\n"
        f"sync-remove-pair = {t['remove_pair']}  # MT\n"
        f"sync-view-conflicts = {t['view_conflicts']}  # MT\n"
        f"sync-conflicts-heading = {t['conflicts_heading']}  # MT\n"
        f"sync-no-conflicts = {t['no_conflicts']}  # MT\n"
        f"sync-winner = {t['winner']}  # MT\n"
        f"sync-side-left-to-right = {t['side_ltr']}  # MT\n"
        f"sync-side-right-to-left = {t['side_rtl']}  # MT\n"
        f"sync-conflict-kind-concurrent-write = {t['kind_cw']}  # MT\n"
        f"sync-conflict-kind-delete-edit = {t['kind_de']}  # MT\n"
        f"sync-conflict-kind-add-add = {t['kind_aa']}  # MT\n"
        f"sync-conflict-kind-corrupt-equal = {t['kind_ce']}  # MT\n"
        f"sync-resolve-keep-left = {t['r_kl']}  # MT\n"
        f"sync-resolve-keep-right = {t['r_kr']}  # MT\n"
        f"sync-resolve-keep-both = {t['r_kb']}  # MT\n"
        f"sync-resolve-three-way = {t['r_3w']}  # MT\n"
        f"sync-resolve-phase-53-tooltip = {t['r_p53']}  # MT\n"
        f"sync-error-prefix = {t['error_prefix']}  # MT\n"
    )


def patch_locale(locale: str, t: dict) -> None:
    path = LOCALES_DIR / locale / "freally.ftl"
    text = path.read_text(encoding="utf-8")
    if "sync-drawer-title" in text:
        print(f"{locale}: already patched, skipping")
        return
    if not text.endswith("\n"):
        text += "\n"
    text += build_block(t)
    path.write_text(text, encoding="utf-8")
    print(f"{locale}: patched")


def main() -> None:
    for locale, t in TRANSLATIONS.items():
        patch_locale(locale, t)


if __name__ == "__main__":
    main()
